### ISSUE TITLE
command completion does not pop-up

### ISSUE THREAD

**Issue by mac-and-linux-user** [SQbQxeKd3JHD8/simple_ConTeXt#5]
+ First: perhabs a bug?
The command completion does not pop-up.
There is no exception in the console window.
I have add an entry under auto_complete_triggers 
in the general Sublime Text settings, like 
the suggested settings.
I'm working with mac osx 10.13.1
and with ubuntu 16.04 LTS (both with Sublime Build 3143).
The behavior is seen also in a new installation of the sublime editor.

+ Second: an enhancement
It would be nice to be able
to see my own definitions (controlsequences) in the pop up.
Is there a possibility to integrate them
by writing them in an html-like-file?

**Comment by gour** [comment]
I also try this possibly wonderful package to assist in writing ConTeX content.

I've the following in my `~/.config/sublime-text-3/Packages/User/simple_ConTeXt.sublime-settings` file:

```
{
   "paths":
  {
    "default": "/home/myuserid/opt/context/tex/texmf-linux-64/bin"
  },
}
```

The above path contains 'context` script, so I assume that's what is rerquired?

Any hint?

**Comment by mac-and-linux-user** [comment]
Many thanks for the answer. The package works well with the binaries. However, when entering a command, the popup menu does not appear. The settings in Preferences.sublime-settings I have carried out according to the information.

**Comment by SQbQxeKd3JHD8** [comment]
Hi @mac-and-linux-user, I've been busy the past few weeks, so this is the first time I've looked at the code in a little while. There are quite a few commits in the repo since the last release (which is what ST/package-control uses), some of which broke things. So I intend to tie up any loose ends, get the current version into a reasonable state, and put up a new release before I do anything else.

As for your specific questions: the pop-ups & completions have two moving parts. Firstly, getting the data for them (what control sequences are there, what arguments do they take, etc.): locate the XML files that come with the context installation, simplify them, and put them into JSON format. I currently put them in the simpleConTeXt package directory, under an `interface` folder (e.g. `~/.config/sublime-text-3/Packages/simple_ConTeXt/interface`) for lack of a better location. So, for debugging, do you have those JSON files? (I put in a `regenerate interface files` command in the more recent commits which is supposed to do exactly this stuff.)

And then the second part is, setting up event listeners, which should 'fire' when e.g. you type in a slash <kbd>\\</kbd>. So there could be some issue with them. Again, this is why I wanna put out a new release: the version I'm working on is different to the one in package control, and I've changed lots of things relating to the pop-ups & completions.

It's funny you mention that enhancement idea, I've been thinking the exact same thing. It would be cool to do it automatically, but I'm not sure how I would go about doing that. It should be pretty straightforward to write a file with extra command definitions in, and tell simpleConTeXt to remember those commands. It's something I plan to add when I can get around to it, I think it's a cool feature and it'll be fun to implement it. Regarding that, do you have any thoughts on where the package should look for such files? I suppose somewhere under the simpleConTeXt package directory would be fine, and we could have a helper command in the command palette to create a blank file in the right place. Hmm. As to the format of them, I'm thinking it could support two formats. The XML-format like the ConTeXt interface files:

```xml
<cd:command name="foo" file="bar.mkiv">
  <cd:arguments>
    <cd:resolve name="keyword-name"/>
    <cd:assignments list="yes" optional="yes">
      <cd:inherit name="setupfoo"/>
    </cd:assignments>
  </cd:arguments>
</cd:command>
```

And the intermediate JSON files (I should definitely revisit these and make them prettier, if we're going to be seeing them more often):

```json
{
  "foo": [
    {
      "fil": "bar.mkiv",
      "con": [
        {
          "ren": "<pun>[</pun>...<pun>]</pun>",
          "opt": false,
          "con": "<typ>NAME</typ>",
          "inh": null
        },
        {
          "ren": "<pun>[</pun>..<com>,</com><key>..</key><equ>=</equ>..<com>,</com>..<pun>]</pun>",
          "opt": true,
          "con": null,
          "inh": "setupfoo"
        }
      ]
    }
  ],
}
```

I'm sure we could tweak the JSON generator to make something a bit prettier, maybe like this:

```json
{
  "foo": [
    {
      "file": "bar.mkiv",
      "content": [
        {
          "text": "[...]",
          "content": "<typ>NAME</typ>",
        },
        {
          "text": "[..,..=..,..]",
          "optional": true,
          "inherits": "setupfoo"
        }
      ]
    }
  ],
}
```

Maybe write some explanation as to how these formats should look, with a couple of examples.

**Comment by theopen-institute** [comment]
I'm having a different problem with similar causes perhaps. My code completion pop-up works fine, but the documentation pop-up doesn't show. My interface folder (on Mac, at ~/Library/Application Support/Sublime Text 3/Packages/simple_ConTeXt) is empty except for an empty folder named "_users_*username*_context_tex_texmf_osx_64_bin".

In the console, I get the following error:
`
Exception in thread Thread-7:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "completions in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/simple_ConTeXt.sublime-package", line 157, in reload_settings_aux
  File "completions in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/simple_ConTeXt.sublime-package", line 163, in save_interface
  File "scripts.save in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/simple_ConTeXt.sublime-package", line 39, in save
  File "scripts.save in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/simple_ConTeXt.sublime-package", line 103, in load_commands
  File "scripts.save in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/simple_ConTeXt.sublime-package", line 120, in load_commands_aux_i
  File "scripts.save in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/simple_ConTeXt.sublime-package", line 182, in do_command
  File "scripts.save in /Users/*username*/Library/Application Support/Sublime Text 3/Installed Packages/simple_ConTeXt.sublime-package", line 511, in get_def
KeyError: 'instance-mathovertextextensible'
`
Any tips?

Thanks for taking the time to make this! It's a huge help and much appreciated.

**Comment by hbcoding** [comment]
First, let me thank you for taking the time enabling ConTexT users to use Sublime Text as an editor.
All the build functionalities and the PDF viewing functionalities are working nicely as intended.
The popus and completions are however not showing.
I am on windows 10 64 bit with the ConTeXt path being "C:\Context\tex\texmf-win64\bin".
The interface directory "C:\Users\XXXXX\AppData\Roaming\Sublime Text 3\Packages\simple_ConTeXt\interface\c__context_tex_texmf_win64_bin" remains empty and the Sublime status line shows no available completions.
I have applied the standard simple_ConTeXt.sublime-settings only modifying "paths "and "PDF_viewer"

Thanks a lot in advance for any help resolving the popup and completions.
